## Data Sources

Data is captured via a series of Case Report Forms (CRFs) developed in compliance with Standard Operating Procedure (SOP) *DM003 CRF Development* and *DM013 CRF Sign-Off* and stored electronically on the [CTRUs Prospect database](https://www.ctru-prospect.shef.ac.uk/) which performs data validation at the point of entry and is compliant with SOPs *DM004 Study Database Development*, *DM005 Central Data Validation* and  *DM006 Data Entry & Import*.  The database will be locked and frozen according to SOP *DM012 Study Database Lock and Retention*.  The SOP *DM009 Data Management Plan* also provides overview of the process of data capture.

## Study Population

### Eligibility, Inclusion and Exclusion

Eligibility, inclusion and exclusion will have been assessed at the recruitment stage (please refer to Study protocol (`r study$protocol_version`) for details of eligibility) and is therefore of little relevance to the Statistical Analysis Plan, although there is some scope for checking the inclusion and exclusion criteria based on collected data.

**NB** The following section is copied directly from the study protocol (`r study$protocol_version`) and is included for completeness and transparency.

#### Inclusion Criteria

> A participant will be included if the child:
>
> * Is aged between 7 and 15 years (based on previous research and extensive PPI recommendations)
> * Attends a mainstream school in years 2-10.
> * The child and parent/ guardian have a sufficient understanding of English to be able to provide informed consent and read the LEGO®-based therapy instructions.
> * Has an ASD clinical diagnosis from a qualified assessing clinician or team based on best-practice guidance leading to an ICD-10 (World Health Organization, 1993) or DSM-IV diagnosis (American Psychiatric Association, 2000)] as reported by the child’s parent/ guardian and in the child’s school records (this may include the school’s special educational needs (SEN) register, an individual education plan (IEP), individual health care plan, my support plan (MSPs), education health care plans (EHCPs), individual learning plans (ILP’s) or equivalent)
> * Scores 15 or higher on the Social Communication Questionnaire.
> * Has the ability to follow and understand simple instructions (as determined by the associated teacher/ TA or parent/ guardian).
>
> A school will be included if:
>
> * It is a mainstream school located in one of the three recruiting sites - Leeds, York, or Sheffield
> * It has not used LEGO®-based therapy with the child in the current or preceding school term.
> * They have at least one child diagnosed with ASD (in line with child inclusion criteria above).

#### Exclusion Criteria

> A participant would not be included in the study if:
>
> * They have physical impairments which would prevent them participating in the activities (assessed by the associated teacher/TA).
> * The child and parent/ guardian do not have a sufficient understanding of English to be able to provide informed consent and read the LEGO®-based therapy instructions.

## Analysis Populations

```{r child = 'tables/analysis_populations.Rmd', include = TRUE}
```

**Per Protocol**
A participant in the Lego-therapy group is defined as Per-Protocol (PP) if...

* They attend 50% of the therapy sessions.

A participant in the normal treatment group can not violate the protocol.

### Role of Populations

**NB** The following section is copied directly from the study protocol (`r study$protocol_version`) and is included for completeness.

> As this trial is a pragmatic cluster RCT, data will be analysed and reported according to both RCT and cluster RCT CONSORT guidelines [@schulz2010b, @campbell2012]. Baseline demographic (e.g. age, gender) and outcome measures (e.g. SDQ) will be assessed for comparability between groups.

No formal statistical tests will be performed for differences, rather visual inspection and comparison of tabulated numbers will be performed and as is best practice, adjustments will be made for important baseline characteristics by including them as co-variates [@bland2011, @senn2006, @vickers2001b, @vickers2001, @kaiser1989].

**INPUT REQUIRED** - It should be possible to say up front what baseline co-variates will be included for adjustment, need these documented.  I'd suggest that for each outcome its corresponding baseline value is included, age and gender too.  Beyond that I'm unsure and require input from the TMG.

> We will use ITT analysis for all outcome measures, that is those who withdraw from the treatment but complete outcome measures will be included in the analyses. This is the most appropriate form of analysis for a pragmatic trial as it maximises the external validity of the data despite the danger of dilution bias [@torgerson2008]. Hence we can evaluate the evidence that the intervention has an effect on the social competence and perceived social isolation of children with ASD within a school setting.

**NB** The Trial Steering Committee (TSC) has advised/requested that a Per-Protocol analyses be performed  as well.  The last Trial Management Group (TMG) meeting 2017-10-25 it was agreed that to meet the protocol participants had to complete 50% of the therapy sessions.  The protocol (`r study$protocol_version`) needs updating to reflect this and once that has been done I'll update the text based on what is written there, or the following suggested text can be appended to the existing statement...

> A Per-Protocol (PP) sensitivity analysis will be performed including only those individuals who attended and completed 50% of the Lego Therapy session, although it is noted that the post-randomisation exclusion of individuals can lead to bias and an inflation in [type I errors (false positive)](https://en.wikipedia.org/wiki/Type_I_and_type_II_errors#Type_I_error) [@lachin2000].
