**NB** Much of the text is copied verbatim from the Study Protocol (`r study$protocol_version`).

## Social Skills Improvement System

The [Social Skills Improvement System (SSIS)](https://www.pearsonclinical.com/education/products/100000322/social-skills-improvement-system-ssis-rating-scales.html) [@gresham2008] is to completed by the associated teacher/ TA at 16 weeks post baseline. The SSIS is a behaviour rating scale that can be completed by parents, teaching staff and appropriate students. It is widely used in national portfolio studies and has been shown to be sensitive to change resulting from interventions in children with ASD. It provides a measurement of social skills (particularly empathy, self-control and communication) as well as internalising and externalising problem behaviours. It also rates academic confidence including motivation to learn. It has good reliability and validity and is validated for use by teachers. The SSIS maps on to the primary objective of the trial (examining the clinical effective of LEGO®-based therapy groups on the social and emotional competence ([including perceived social skills, challenging behaviours and academic confidence] of children with ASD in a mainstream school setting). The associated teacher/ TA will be asked to complete the SSIS at baseline, 16 and 52 weeks after baseline.

**INPUT REQUIRED** I haven't yet been able to access the cited manual so am unable to say how many questions there are, how responses are weighted/scored and how the overall statistic is calculated.


## Child Health Utility 9D

The Child Health Utility 9D (CHU-9D) [@stevens2009, @stevens2011] is a paediatric generic preference basede measure of health related quality of lfe.  The questionnaire consists of 9 dimensions each with 5 possible response.  A utility score is calculated by assigning utility values to each response and then summing these values.  A CHU-9D score can only be calculated if all questions have been answered.  The CHU-9D utility score ranges from 0.33 to 1 where higher scores represent better health related quality of life.  It is expected the CHU-9D will be a more valid and reliable measure with younger children than the EQ-5D-Y [@furber2015].

**ToDo** Tease out details of how many questions, how responses are weighted/scored and how the overall statistic is calculated.

## EQ-5D-Y (3L Proxy)

The [EQ-5D-Y](https://euroqol.org/eq-5d-instruments/eq-5d-y-about/) [@wille2010-8, @ravens-sieberer2010-4] is a child friendly version of the [EQ-5D]() which consists of five questions measuring mobillity, self-care, usual activities, pain/discomfort and anxiety/depression, each with three possible responses (`no problems`, `some problems`, `lots of problems`).  The scores are assigned utility values and comnbined to give a value index score.  In the absence of specific utility value sets for the EQ-5D-Y the EQ-5D-3L can not be used [@kind2015-10] so such instances will be excluded.  The score ranges from -0.22 to 1.00 (a score of zero means death, 1 is full health and a negative score is a state worse than death).  The score will not be calculated if any items are missing.  The algorithm for scoring can be found in the [EQ-5D-Y User Manual](https://euroqol.org/wp-content/uploads/2016/09/EQ-5D-Y_User_Guide_v1.0_2014.pdf).  The EQ-5D Visual Analogue Scale (VAS) indicatges your health state today as measured on a scale from 0 (worst) to 100 (best).


## Asher Loneliness Scale

The Asher Loneliness Scale [@asher1985-8] is a friendship subscale that will be used to measure perceived social isolation. This self-report scale consists of 24 items. Respondents mark a 1-to-5 scale indicating the frequency with which they felt that way, ranging from never to always.Friendship and significant other subscales will be used to assess the child’s perceived social support. The full questionnaire is a short 12 item social support scale that assesses the adequacy of a person’s perceived social support from family, friends and significant others. For the purposes of this study, we will assess the 8 items relating to support from friends and a significant other (within the school setting).

**INPUT REQUIRED** - be useful to have greater detail on what sounds like a subset of repsonses are to be used.

## Multidimensional Scale of Perceived Social Support

The Multidimensional Scale of Perceived Social Support [@zimet1988, @dahlem1991]. Friendship and significant other subscales will be used to assess the child’s perceived social support. The full questionnaire is a short 12 item social support scale that assesses the adequacy of a person’s perceived social support from family, friends and significant others. For the purposes of this study, we will assess the 8 items relating to support from friends and a significant other (within the school setting) is a friendship subscale that will be used to measure perceived social isolation. This self-report scale consists of 24 items. Respondents mark a 1-to-5 scale indicating the frequency with which they felt that way, ranging from never to always.

**INPUT REQUIRED** - above is copied from the protocol, seems incomplete "[SOMETHING?] is a frienship subscale...".

## Strengths and Difficulties Questionnaire

**INPUT REQUIRED** - Protocol only says the tool is to be used, doesn't describe what it does nor how it is used.  Having skimmed the paper suggest the following..

> The Strengths and Difficulties Questionnaire [@goodman1997] is a single page screening tool that provides balanced coverage of children and young people's aged 4-16 behaviours , emotions, and relationships and has been demonstrated to be highly correlated to the more established Rutter questionnaires [@elander1996-7].  There are 25 items each with three possible repsonses and scores *Not True* (score = 0), *Somewhat True* (score = 1) and *Certainly True* (score = 2).  These are summed to give a score between 0-40.  For further details refer to Appendix B of [@goodman1997]

## Social Communication Questionnaire

The [Social Communication Questionnaire (SCQ)](https://www.wpspublish.com/store/Images/Downloads/Product/SCQ_Manual_Chapter_1.pdf) (**CITATION**) is a 40-item, parent completed questionnaire derived from the Autism Diagnostic Interview–Revised [@lord1994-10]. The recommended cut-off to suggest it is likely an individual has ASD is 15. The SCQ has excellent sensitivity and reliability [@chandler2007-10].  It will only be completed as an eligibility check prior to baseline.



## Acceptability Questionnaire

**INPUT REQUIRED** - What statistical analysis of the Acceptability Questionnaire is required?


```{r child = 'tables/questionnaires.Rmd', eval = TRUE}
```
