## Pilot Endpoint

As detailed above, the internal pilot phase will be considered successful and the study will continue if at 10 months...

- 90 participants have been recruited.
- 40 participants have the primary endpoint of 16 weeks.
- 28 of these will have outcome measures available.

**INPUT REQUIRED** Protocol states (as above) that the available data...

> will be used to assess feasibility of continuing the trail.

...but is not explicit on what the criteria for assessment will be, is it simply that 28 outcome measures of SSIS completed at 16 weeks by Teacher/Trainer will be available?

## Primary Outcome

* [Social Skills Improvement System (SSIS)](https://www.pearsonclinical.com/education/products/100000322/social-skills-improvement-system-ssis-rating-scales.html) [@gresham2008] assessed by the Teacher/Teaching Assistant at 16 weeks.

## Secondary Outcomes

A host of additional assessment tools are being used and form the basis of the Secondary Outcomes.  Details of their scoring and the handling of missing data are detailed in Section ###).


* Multidimensional Scale of Preceived Social Support [@zimet1988][@dahlem1991].
* Asher Loneliness Scale [@asher1985-8].
* Child Health Utility 9D [@stevens2009][@stevens2011].
* Demograhpics (assessed by the Parents).
* Demograhpics (assessed by the Interventionst).
* Social Communication Questionnaire (**CITATION**).
* Social Skills Improvement System [@gresham2008] (assessed by the Parents).
- Strengths and Difficulties Questionnaire [@goodman1997] (assessed by the Parents).
- Strengths and Difficulties Questionnaire [@goodman1997] (assessed by the Teacher/Teaching Assistant).
- Bespoke Resource use Questionnaire (assessed by the Parents).
- Bespoke Resource use Questionnaire (assessed by the Teacher/Teaching Assistant).
- Bespoke Adverse Events Questionnaire (assessed by the Parents).
- Bespoke Adverse Events Questionnaire (assessed by the Teacher/Teaching Assistant).
- EQ-5D-Y (3L proxy) [@wille2010-8] [@ravens-sieberer2010-4].
- Bespoke Acceptability Questionnaire.
- Social Skills Improvement System [@gresham2008]  (assessed by the Teacher/Teaching Assistant at 52 weeks).


A table of all assessment tools, who they are assessing and administered by and the time-points at which they are used are detailed in the table below which combines Tables 1-4 from the Study Protocol (v3.0 2017-11-15).


| Completed by...  | Measure                | Time points completed | Administered by... |
|------------------|------------------------|-----------------------|--------------------|
| Child Participant | Multidimensional Scale of Perceived Social Support (8 items relating to support from friends) | Baseline | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Asher Loneliness Scale | Baseline              | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Child Health Utility 9D| Baseline              | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
| Parents          | Demographics           | Consent               | Research assistant |
|                  | Social Communication Questionnaire | Consent   | Research assistant |
|                  | Social Skills Improvement System   | Baseline  | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Strengths and Difficulties Questionnaire | Baseline | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Bespoke resource use questionnaire | Baseline  | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Bespoke adverse events questionnaire | 16 weeks| Research assistant |
|                  | EQ-5D-Y  (3L proxy)    | Baseline              | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Bespoke acceptability questionnaire (intervention group only) | 16 weeks | Research assistant |
| Teacher/Teaching Assistant | Social Skills Improvement System | Baseline | Research assistant |
|                  |                        | 16 weeks (**Primary**)| Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Strengths and Difficulties Questionnaire | Baseline | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Bespoke resource use questionnaire | Baseline  | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Bespoke adverse events questionnaire | 16 weeks| Research assistant |
| Interventionist Teacher/Teaching Assistant | Demographics | Baseline | Research assistant |
|                  | Bespoke acceptability questionnaire  | 16 weeks | Research assistant |
|                  | Bespoke resource use questionnaire   | After each therapy session | Interventionist |
|                  | Bespoke adverse events questionnaire | After each therapy session | Interventionist |
|                  | Fidelity checklist                   | After each therapy session | Interventionist |
