This study is a cluster RCT to investigate the effectiveness of LEGO®-based therapy for children with ASD. There will be an internal pilot study which will run for 10 months to examine the feasibility of recruitment. The pilot period will run for 10 months, at which point we expect to have recruited n=120 of which one third (n=40) will have reached the primary endpoint. Stop/Go criteria based on 75% of recruitment target (n=90) and 70% of the primary outcome measures (n=28) will be used to assess feasibility of continuing the trial. There is a nested economic evaluation, qualitative component and assessment of fidelity and acceptability.

### Primary Objective

The primary objective of this trial is to examine the clinical effectiveness of LEGO®-based therapy groups on the social and emotional competence (including perceived social skills, challenging behaviours and academic confidence) of children with ASD within a mainstream school setting, when compared with usual support provided for children with ASD.

### Secondary Objectives

The secondary objectives of this trial are to:
1. Examine the clinical effectiveness of LEGO®-based therapy groups on the perceived social isolation and loneliness of children with ASD within the school setting, when compared with usual support provided.
2. Examine the cost-effectiveness of LEGO®-based therapy groups in terms of health-related quality of life and cost utility at 16 and 52 weeks.
3. Determine if the impact of LEGO®-based therapy is sustainable into the next academic year by measuring effectiveness 52 weeks after baseline.
4. Examine the acceptability of the intervention at follow-up points using a purpose designed questionnaire and telephone interviews.
5. Examine treatment fidelity through independent observation of treatment sessions across schools.


### Outcome Measures

| Completed by...  | Measure                | Time points completed | Administered by... |
|------------------|------------------------|-----------------------|--------------------|
| Child Participant | Multidimensional Scale of Perceived Social Support (8 items relating to support from friends) | Baseline | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Asher Loneliness Scale | Baseline              | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Child Health Utility 9D| Baseline              | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
| Parents          | Demographics           | Consent               | Research assistant |
|                  | Social Communication Questionnaire | Consent   | Research assistant |
|                  | Social Skills Improvement System   | Baseline  | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Strengths and Difficulties Questionnaire | Baseline | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Bespoke resource use questionnaire | Baseline  | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Bespoke adverse events questionnaire | 16 weeks| Research assistant |
|                  | EQ-5D-Y  (3L proxy)    | Baseline              | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Bespoke acceptability questionnaire (intervention group only) | 16 weeks | Research assistant |
| Teacher/Teaching Assistant | Social Skills Improvement System | Baseline | Research assistant |
|                  |                        | 16 weeks (**Primary**)| Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Strengths and Difficulties Questionnaire | Baseline | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Bespoke resource use questionnaire | Baseline  | Research assistant |
|                  |                        | 16 weeks              | Research assistant |
|                  |                        | 52 weeks              | Research assistant |
|                  | Bespoke adverse events questionnaire | 16 weeks| Research assistant |
| Interventionist Teacher/Teaching Assistant | Demographics | Baseline | Research assistant |
|                  | Bespoke acceptability questionnaire  | 16 weeks | Research assistant |
|                  | Bespoke resource use questionnaire   | After each therapy session | Interventionist |
|                  | Bespoke adverse events questionnaire | After each therapy session | Interventionist |
|                  | Fidelity checklist                   | After each therapy session | Interventionist |

### Sample Size

**NB** The following section is copied directly from the study protocol and whilst it it has little bearing on the statsitical analyses themselves it is included for completeness.

The sample size calculation is based on the (Reichow et al., 2012) Cochrane review which reported on five studies that examined the effects of social skills groups on social competence. This context was selected as the best indicator of realistic clinical effectiveness on the basis that if the proposed intervention was to be viable it needs to be at least as effective as running a social skills group in school. Of the five studies included in this review, four were RCTs and reported standardised measures of social competence which could be synthesised through meta-analysis techniques. The weighted mean standardised difference in social competence between group treatment and services as usual was 0.47 (95% confidence interval from 0.16 to 0.78). Reichow, et al., (2012) argued that this average effect size of almost 0.5 of an SD corresponds to a clinically significant change, 'to put these gains in more concrete terms, if measuring everyday socials skills using the Vineland (Sparrow 2005) for example an average participant from these studies would increase their repertoire of social skills from 123 to 147 after participating in the social skills group which is a clinically significant increase'.  Calculations using this standardised effect size of 0.47, 90% power and 5% two sided significance results in a sample size of 97 participant groups per condition or 194 participant groups in total. Attrition rates varied between 0% and 16% for the studies included in the (Reichow et al., 2012) Cochrane review. As such, a conservative estimate of 16% inflates the sample to a final size of 116 participant groups per condition or 232 in total. To account for trainer/school effects and a cluster size of approximately 2 participants per cluster (ICC=0.01), based on the findings of the ASSSIST feasibility study conducted in the York area (Wright et al., 2016) this figure was further inflated and rounded up to 120 participants groups per condition or 240 in total. We anticipate recruitment of 12 per month across all sites and have retention rate of 84% at 16 week follow-up. The pilot period will run for 10 months, at which point we expect to have recruited n=120 of which one third (n=40) will have reached the primary endpoint. Stop/Go criteria based on 75% of recruitment target (n=90) and 70% of the primary outcome measures (n=28) will be used to assess feasibility of continuing the trial.
