```{r distribution, cache = FALSE, echo = FALSE, warnings = FALSE, results = 'hide', eval = TRUE}
## Download data provided by Dani.
eligible_students <- list()
eligible_students$gs         <- googlesheets::gs_title('School EOI list  - Anonymised 14082017.xlsx')
eligible_students$raw        <- eligible_students$gs %>%
                                gs_read(ws = 'Sheet1',
                                        range = cell_cols(1:5))
names(eligible_students$raw) <- c('school_id', 'Area', 'Eligible', 'lego_therapy', 'Type')
                                  ## 'X1', 'X2', 'X3', 'X4', 'X5')
eligible_students$df         <- eligible_students$raw %>%
                                dplyr::select(school_id, Area, Eligible, lego_therapy, Type) %>%
                                mutate(Area         = factor(Area,
                                                             levels = c(1, 2, 3),
                                                             labels = c('Leeds', 'York', 'Sheffield')),
                                       Eligible     = ifelse(Eligible == 'TBA',
                                                             yes = NA,
                                                             no  = as.numeric(Eligible)),
                                       ## lego_therapy = case_when(lego_therapy == 'No'  ~ 'No',
                                       ##                          grepl('Yes',
                                       ##                                lego_therapy,
                                       ##                                ignore.case = TRUE) ~ 'Yes'),
                                       ## lego_therapy = factor(lego_therapy,
                                       ##                       labels = c('No', 'Yes')),
                                       Type         = factor(Type,
                                                            labels = c('Primary', 'Primary + Secondary', 'Secondary')))
## Tables
eligible_students$table_area_type <- eligible_students$df %$%
                                     table(Area, Type)
eligible_students$table_type_eligible <- eligible_students$df %$%
                                         table(Type, Eligible)
## Figures
eligible_students$figure_area_type <- eligible_students$df %>%
                                      ggplot(aes(x = Eligible, fill = Type)) +
                                      geom_histogram() +
                                      facet_wrap(~Area) +
                                      ylab('N') +
                                      theme_bw()
eligible_students$figure_type <- eligible_students$df %>%
                                 ggplot(aes(x = Eligible, fill = Type)) +
                                 geom_histogram() +
                                 ## facet_wrap(~Type) +
                                 ylab('N') +
                                 theme_bw()
eligible_students$figure_area <- eligible_students$df %>%
                                 ggplot(aes(x = Eligible, fill = Area)) +
                                 geom_histogram() +
                                 ## facet_wrap(~Type) +
                                 ylab('N') +
                                 theme_bw()
## Summary numbers for inclusion in text
eligible_students$n_sites    <- eligible_students$df %>%
                                nrow()
eligible_students$n_eligible <- eligible_students$df[!is.na(eligible_students$df$Eligible),] %>%
                                nrow()
save(eligible_students,
     file = '../data/eligible_students.RData')

```

The following code generated the randomisation schedule.

```{r analysis, cache = FALSE, echo = TRUE, warnings = FALSE, results = 'hide', eval = TRUE}
n           <- 50
num_levels  <- 2
block_sizes <- 5
primary_small <- blockrand(n            = n,
                           num.levels   = num_levels,
                           levels       = c('LEGO Therapy', 'Standard Care'),
                           id.prefix    = 'SCH',
                           stratum      = 'Primary; < 6',
                           block.sizes  = block_sizes)
block_sizes <- 1
primary_large <- blockrand(n          = n,
                           num.levels = num_levels,
                           levels     = c('LEGO Therapy', 'Standard Care'),
                           id.prefix = 'SCH',
                           stratum    = 'Primary; >= 6',
                           block.sizes = block_sizes)
block_sizes <- 5
secondary_small <- blockrand(n          = n,
                             num.levels = num_levels,
                             levels     = c('LEGO Therapy', 'Standard Care'),
                             id.prefix = 'SCH',
                             stratum    = 'Secondary; < 6',
                             block.sizes = block_sizes)
block_sizes <- 1
secondary_large <- blockrand(n          = n,
                             num.levels = num_levels,
                             levels     = c('LEGO Therapy', 'Standard Care'),
                             id.prefix = 'SCH',
                             stratum    = 'Secondary; >= 6',
                             block.sizes = block_sizes)
randomisation <- rbind(primary_small,
                       primary_large,
                       secondary_small,
                       secondary_large)
## Originally when developing the code unique prefixes were used within
## exach strata, but this would mean that centres/schools could be
## identified based on these and for some reason the Statistician has to
## remain blind, therefore modify the id to be unique and unidentifiable
## across all strata
randomisation <- randomisation %>%
                 mutate(row = rownames(.),
                        id = case_when(nchar(row) == 1 ~ paste0('SCH', '00', row),
                                       nchar(row) == 2 ~ paste0('SCH', '0', row),
                                       nchar(row) == 3 ~ paste0('SCH', row))) %>%
                 dplyr::select(-row)

```
